{
  "before_script": [
    "composer self-update", 
    "composer install --prefer-source --no-interaction --dev"
  ], 
  "notifications": {
    "on_failure": "always", 
    "on_success": "never"
  }, 
  "matrix": {
    "allow_failures": [
      {
        "php": 5.5999999999999996
      }, 
      {
        "php": "hhvm"
      }
    ], 
    "fast_finish": true
  }, 
  "language": "php", 
  "script": "phpunit", 
  "php": [
    5.4000000000000004, 
    5.5, 
    5.5999999999999996, 
    "hhvm"
  ]
}
